### ISSUE TITLE
Vue axios 도입

### ISSUE THREAD

**Issue by Junroot** [Junroot/Nomat#34]
- profile 에 따른 base url 설정
  - local: `http://localhost:8080`
  - dev: 미정
  - prod: 미정

**Comment by Junroot** [comment]
1. profile에 따라 env variable 다르게 설정하기
2. npm에 axios 의존성 추가
3. 메인화면에서 axios로 요청 보내지는지 테스트

**Comment by hsrst** [comment]
환경 변수 설정 및 Axios 요청 테스트 완료.
