### ISSUE TITLE
로그인 페이지 UI 설계

### ISSUE THREAD

**Issue by Junroot** [Junroot/Nomat#52]

**Comment by hsrst** [comment]
로그인 화면은 언제 뜨는가?
- 로그인하지 않은 상태에서 방을 눌렀을 때
- 링크를 클릭했을 때


어떤 걸 보여주나?
- 우리 서비스 이름&로고
- 노맞 게임에 대한 설명
- 로그인이 필요합니다
- 로그인 서비스 버튼들

**Comment by hsrst** [comment]
로그인 버튼은 동그라미로
